/**
 * 
 */
package com.srans.nestserver.util;

/**
 * @author user
 *
 */
public class MailTemplates {
	
	public static final String TENANT_REGISTRATION_TEMPLATE = "<html><body style='margin: 0; padding: 0;'><table align='center' border='0' cellpadding='0' cellspacing='0' width='100%' style='border-collapse: collapse;'>\r\n" + 
			"     <tr>  <td  align='left'  bgcolor='#f5f5f5'  style='padding: 20px 0px 15px 50px;'> Dear \r\n ##USER_NAME## "  + 
			"     </td> </tr>\r\n" + 
			"    <tr>  <td align='left' bgcolor='#f5f5f5' style= ' text-align: justify; padding: 5px 0px 5px 20px '> you are successfully registered.\r\n" + 
			"     Your new Nidos account has been created. Welcome to the NIDOS community.<br>\r\n" + 
			"     Please logon to your account using your username and temporary password.\r\n" + 
			"     \r\n" + 
			"       </td> </tr>\r\n" + 
			"     <tr>  <td> \r\n" + 
			"    <table cellpadding='0' cellspacing='0'  width='75%'>\r\n" + 
			"     <tr><td align='center' bgcolor='#f5f5f5' style='padding: 20px 0 15px 0'> Username :</td><td align='center' bgcolor='#f5f5f5' style='padding: 20px 0 15px 0'> ##USER_NAME##</td></tr>\r\n" + 
			"     <tr><td align='center' bgcolor='#ffffff' style='padding: 20px 0 15px 0'> Password :</td><td align='center' bgcolor='#ffffff' style='padding: 20px 0 15px 0'>##PASSWORD##</td></tr>\r\n" + 
			"     <tr><td align='center' bgcolor='#f5f5f5' style='padding: 20px 0 15px 0'> Hostel Name :</td><td align='center' bgcolor='#f5f5f5' style='padding: 20px 0 15px 0'>##HOSTEL_NAME##</td></tr>\r\n" + 
			"     <tr><td align='center' bgcolor='#ffffff' style='padding: 20px 0 15px 0'>  Room Number :</td><td align='center' bgcolor='#ffffff' style='padding: 20px 0 15px 0'>##ROOM_NUMBER##</td></tr>\r\n" + 
			"     <tr><td align='center' bgcolor='#f5f5f5' style='padding: 20px 0 15px 0'>  Floor Number :</td><td align='center' bgcolor='#f5f5f5' style='padding: 20px 0 15px 0'>##FLOOR_NUMBER##</td></tr>\r\n" + 
			"    <tr><td align='center' bgcolor='#ffffff' style='padding: 20px 0 15px 0'>  Room Rent  :</td><td align='center' bgcolor='#ffffff' style='padding: 20px 0 15px 0'> ##ROOM_RENT##</td></tr>\r\n" + 
			"    </table>\r\n" + 
			"      </td> </tr>\r\n" + 
			"    <tr><td align='left'  bgcolor='#f5f5f5'  style='padding: 20px 0px 15px 50px;'>This is an autogenerated emial, please dont reply to this thread.<br>Thank You<br><br>--Regards<br>NIODS Community<br>Hyderabad</td></tr> \r\n" + 
			"    </table>\r\n" + 
			"     </body></html>";

}
